Upd
dandimog/Marketplace pull request #44
Opened 2021-06-03 13:54 UTC by dandimog

2021-06-03 14:42 UTC, JuliaNortman approved these changes

2021-06-03 14:46 UTC, JuliaNortman requested changes
Cannot be merged automatically
You should resolve conflicts

2021-06-05 10:51 UTC, MaxxMorozov reviewed
- what's the PR about? the name isn't informative, no description
- in general, the PR is too large. Looks like just "all my work from the last week". PR should be as small as possible - 1 atomic piece of work, 1 feature, 1 bugfix, 1 refactoring, etc.
- I've left 1 type of each comment just FYI. there's a bunch of issues of the same type throughout the PR

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/account/forgot-password/forgot-password.component.ts
>            console.log(error);
don't commit such sensitive logs

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/filter/filter.component.html
> +              [checked]="activeRadioButton == status" (change)="onChange($event)">
`===` works faster
https://codeburst.io/javascript-double-equals-vs-triple-equals-61d4ce5a121a

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/filter/filter.component.html
> +            <input type="radio" class="custom-control-input" value={{status}} name="isActive" id={{status}}
it's more readable to write 1 attr = 1 line

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/filter/filter.component.html
> +</div> -->
don't commit commented out code (at least you can add TODO with a description if you plan to use it later)

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/filter/filter.component.html
> +      <div class="">
better add some class here to make CSS selectors more specific

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/manager-list/manager-list.component.ts
> +  readonly status_list: string[] = ['all', 'active', 'terminated'];
by convention, js var names are in camelCase

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/filter/filter.component.ts
> +  @Output() results: EventEmitter<any> = new EventEmitter<any>();
specify the type

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/filter/filter.component.ts
> +      .subscribe((results: UserDto) => {
don't forget to unsubscribe

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/filter/filter.component.ts
> +        this.service.pageSource.next(results.currentPage);
we get some info from the service and then send it back. The service can do it itself. If we can delegate some data-processing work from a component to a service, then better do it. The component should be as small as possible and do only UI-rendering work

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/filter/filter.component.ts
> +  filterStatus(status: string, init: boolean) {
all your class members are public. But some of them are used only inside of the class and might be made private

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/search/search.component.ts
> +    fromEvent(this.el.nativeElement, 'keyup')
it's safer and faster not to listen to `keyup` events, but to utilize angular's built-in event emitters. Any HTML input has a bunch of outputs from js-native events, like `(change)`, `(click)`, `(blur)`, etc. You can just use 1-way output binding to listen to them
(the current option is not an error, as well)

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/account/_components/password.form.component.ts
> +  get getForm(): { [p: string]: AbstractControl } { return this.form.controls; }
`Record<string, AbstractControl>`

https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeystype

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/account/_components/password.form.component.ts
> +          .subscribe({
`subscribe` inside of the `subscribe` (moreover, without unsubscriptions) is a source of memory leaks and unexpected async errors. Leverage the RxJS flattening operators:

https://ramya-bala221190.medium.com/simple-example-for-rxjs-flattening-operators-2456628e4c07

http://alanpryorjr.com/2019-05-15-rxjs-flattening-operators/#:~:text=In%20reality%2C%20the%20flattening%20operators,observable%20that%20is%20emitting%20values.&text=Contrast%20this%20with%20map%20%2C%20which,value%20(not%20another%20observable).

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/system-accounts/register-stuff/register-stuff.component.ts
> +  private mapToStaffMember(o: any): StaffMember {
argument types

2021-06-05 10:51 UTC, MaxxMorozov commented on marketplace-client/src/marketplace/src/app/_services/system-account.service.ts
> +  buildQueryParams(filter: string, search: string, page: number): HttpParams {
don't forget about access modifiers

2021-06-09 07:43 UTC, closed without merging